# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20180625_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='commerce.Location'),
            preserve_default=False,
        ),
    ]
