# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
