# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='locked',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
