# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=10),
            preserve_default=False,
        ),
    ]
